yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('create/', views.post_create, name='post_create'),
    path('', views.index, name='main'),
    path('group/<slug>/', views.group_posts, name='url_group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'

handler500 = 'core.views.server_error'

handler403 = 'core.views.permission_denied'

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField('title group', max_length=200)
    slug = models.SlugField('uniq address group', unique=True)
    description = models.TextField('text Area group')

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор поста',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа для поста',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        'Дата комментария',
        auto_now_add=True
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:

        model = Post

        fields = ('text', 'group', 'image')
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
            'image': 'Картинка для сообщения',
        }


class CommentForm(forms.ModelForm):
    class Meta:

        model = Comment

        fields = ('text',)
        help_texts = {
            'text': 'Текст комментария',
        }

yatube/posts/views.py
from django.shortcuts import redirect, render
from .models import Follow, Post, Group, User, Comment
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required


POSTS_PER_PAGE = 10


def index(request):

    posts = Post.objects.all()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }

    return render(request, 'posts/index.html', context)


def group_posts(request, slug):

    group = get_object_or_404(Group, slug=slug)
    title = f'Записи сообщества {group.title}'
    posts = group.posts.all()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'group': group,
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):

    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=author)
    cnt_posts = posts.count()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user,
            author=author) or None
    else:
        following = None

    context = {
        'cnt_posts': cnt_posts,
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post=get_object_or_404(Post, id=post_id))
    posts_author = Post.objects.filter(author=post.author)
    cnt_posts = posts_author.count()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
        'cnt_posts': cnt_posts,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):

    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user

        post.save()

        return redirect('posts:profile', username=request.user)

    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):

    post = get_object_or_404(Post, id=post_id)
    if request.user == post.author:
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post or None)
        if form.is_valid():
            post.author = request.user
            post.save()
            return redirect('posts:post_detail', post_id=post_id)
        else:
            context = {
                'form': form,
                'is_edit': True,
            }
        return render(request, 'posts/create_post.html', context)
    else:
        return redirect('login')


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    '''Отображение постов подписанных авторов '''
    title = 'Новые посты ваших авторов'
    follow_author = Follow.objects.filter(user=request.user).values_list(
        'author_id',
        flat=True
    )
    posts = Post.objects.filter(author_id__in=follow_author)
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    '''Подписаться на автора'''
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(
            user=get_object_or_404(User, username=request.user),
            author=get_object_or_404(User, username=username)
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    '''Дизлайк, отписка'''
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
  {% if is_edit %}
  Редактировать запись
  {% else %}
  Добавить новый пост
  {% endif %}
{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
            Редактировать запись
            {% else %}
            Добавить новый пост
            {% endif %}         
          </div>
          <div class="card-body">        
            <form method="post" enctype="multipart/form-data" action="">
              {% csrf_token %}
            
              <input type="hidden" name="" value="">            
              <div class="form-group row my-3 p-3">
                {{ form }}
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}   
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %} 
{% load thumbnail %}
{% load cache %}
{% block content %}
    
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">     
    <h1>
      {{ title }}
    </h1>
    <article>
    {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "480x200" crop="center" upscale=False as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
      {% if post.group %}
        <a href="{% url 'posts:url_group' post.group.slug %}">все записи группы</a>
      {% else%}     
        <p>У поста нет группы</p>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    </article>
  </div>  
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}
{% load thumbnail %}
{% block content %}
  <div class="container py-5">   
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description}}
    </p>
    <article>
      {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "480x200" crop="center" upscale=False as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
      {% if post.group %}
      <a href="{% url 'posts:url_group' post.group.slug %}">все записи группы</a>
        {% else%}     
          <p>У поста нет группы</p>
        {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    </article>
  </div>  
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}Последние обновления на сайте{% endblock %} 
{% load thumbnail %}
{% load cache %}
{% block content %}

  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">     
    <h1>
      Последние обновления на сайте
    </h1>
    <article>
      {% include 'posts/includes/switcher.html' %}
      {% cache 20 index_page %}
      {% for post in page_obj %}
      <ul>
        <li>
          Автор: <a href="{% url 'posts:profile' post.author.username %}"> {{ post.author.get_full_name }} </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "480x200" crop="center" upscale=False as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
      {% if post.group %}
        <a href="{% url 'posts:url_group' post.group.slug %}">все записи группы</a>
      {% else%}     
        <p>У поста нет группы</p>
      {% endif %}      
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}
    </article>
  </div>  
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load user_filters %}

{% block title %}{{ post.text|truncatechars:30 }}{% endblock %}
{% load thumbnail %}
{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y"  }}
            </li>
            <!-- если у поста есть группа -->   
              <li class="list-group-item">
              {% if post.group %}{{ post.group.title }}:
                <a href="{% url 'posts:url_group' post.group.slug %}">все записи группы</a>
              {% else%}     
                <p>У поста нет группы</p>
              {% endif %}
              </li>
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ cnt_posts }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          {% if request.user.is_authenticated and post.author.username == request.user.username %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            Редактировать запись
          </a>
          {% endif %}
          {% if user.is_authenticated %}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post.id %}">
                  {% csrf_token %}      
                  <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
            </div>
          {% endif %}

          {% for comment in comments %}
            <div class="media mb-4">
              <div class="media-body">
                <h5 class="mt-0">
                  <a href="{% url 'posts:profile' comment.author.username %}">
                    {{ comment.author.username }}
                  </a>
                </h5>
                  <p>
                  {{ comment.text }}
                  </p>
                </div>
              </div>
          {% endfor %} 
        </article>
      </div> 
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}Профайл пользователя{{ author.username }}{% endblock %}
{% load thumbnail %}
{% block content %}
  <div class="container py-5">        
  <h1>Все посты пользователя {{ author.first_name }} {{ author.last_name }}</h1>
  <h3>Всего постов: {{ cnt_posts }}</h3>
  {% if request.user.is_authenticated and author != request.user %}
    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
  {% endif %}
 {% endif %}
</div>
  {% for post in page_obj %}
    <article>      
      <ul>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "480x200" crop="center" upscale=False as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>       
  </article> 
  {% if post.group %}
  <a href="{% url 'posts:url_group' post.group.slug %}">все записи группы</a>
{% else%}     
  <p>У поста нет группы</p>
{% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %} 